/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa.Ventanas;
import java.io.File;
import javax.swing.JOptionPane;
import proyecto.Grafo;
import static proyecto.Proyecto.encontrar;
import static proyecto.Proyecto.extraerGrafo;
import static proyecto.Proyecto.guardarGrafo;
import static proyecto.Proyecto.miGrafo;
import proyecto.Usuario;

/**
 *
 * @author donat
 */
public class Ventana2_2 extends javax.swing.JFrame {
        private static Grafo miGrafo;
        public static int pestana;
        public static File guardado_automatico = new File("src\\Archivos\\guardado_automatico.txt");
    
    public Ventana2_2() {
        
//        this.setLocationRelativeTo(null);
        initComponents();
    }
    public void Ventanatext(String texto, int num){
        hacer.setText(texto);
        pestana =num;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dialogo = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        idtextoo = new javax.swing.JLabel();
        nombreamigo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        devolver = new javax.swing.JButton();
        hacer = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pulsa aqui para volver");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 130, 30));

        dialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dialogo 8 bit peq.png"))); // NOI18N
        getContentPane().add(dialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        limpiar.setBorderPainted(false);
        limpiar.setContentAreaFilled(false);
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 30, 30));

        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 30, 30));

        idtextoo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idtextoo.setForeground(new java.awt.Color(0, 0, 0));
        idtextoo.setText("ID Usuario:");
        getContentPane().add(idtextoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));

        nombreamigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreamigo.setForeground(new java.awt.Color(0, 0, 0));
        nombreamigo.setText(".");
        nombreamigo.setFocusable(false);
        getContentPane().add(nombreamigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 140, 20));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 70, -1));

        devolver.setBorderPainted(false);
        devolver.setContentAreaFilled(false);
        devolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolver.setFocusable(false);
        devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverActionPerformed(evt);
            }
        });
        getContentPane().add(devolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 30, 20));

        hacer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hacer.setForeground(new java.awt.Color(0, 0, 0));
        hacer.setText("aqui");
        getContentPane().add(hacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 30));

        idtext.setBackground(new java.awt.Color(255, 255, 255));
        idtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idtext.setForeground(new java.awt.Color(0, 0, 0));
        idtext.setText("000");
        getContentPane().add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jLabel4.setFocusable(false);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8bitfondo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        idtext.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed

        miGrafo = extraerGrafo(guardado_automatico);
        guardarGrafo(miGrafo, guardado_automatico);
        try{
            if (pestana==1) {
                JOptionPane.showMessageDialog(null, pestana);
                miGrafo.eliminarUsuario(Integer.parseInt(idtext.getText()));
                guardarGrafo(miGrafo, guardado_automatico);
            }else{
                Ventana2 v2 = new Ventana2();
                int peso = Integer.parseInt(JOptionPane.showInputDialog("Cuantos años lleva su amistad?:\n"));
                miGrafo.insertarAristaValor(pestana, Integer.parseInt(idtext.getText()), peso);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, introduzca bien los datos");
                
                }  
        

    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nombreamigo.setText(encontrar(Integer.parseInt(idtext.getText())));
        
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverActionPerformed
           
            if (pestana==1) {
                dispose();
            Ventana1 v1 = new Ventana1(true);
            v1.setVisible(true);
        } else if (pestana<2) {
            dispose();
            Ventana2 v2 = new Ventana2();
            v2.setVisible(true);
        }
            guardarGrafo(miGrafo, guardado_automatico);
        
        
    }//GEN-LAST:event_devolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2_2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton devolver;
    private javax.swing.JLabel dialogo;
    private javax.swing.JLabel hacer;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel idtextoo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel nombreamigo;
    // End of variables declaration//GEN-END:variables
}
